module.exports = {
	accounts_table: 'accounts_table',
	admin_accounts: 'admin_Accounts',
	admin_profile: 'admin_Profile',
	employee_profile: 'employee_profile',
	driver_profile: 'driver_profile',
	user_profile: 'user_profile',
	establishments: 'establishments',
	companion_table: 'companion_table',
	travel_history: 'travel_history',
	vehicle_table: 'vehicles',
	passengers: 'passengers_table',
	employee_scanned: 'employee_scanned',
	address_table: 'address_table',
}
